version: "3.9"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: forum
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
  server:
    build: .
    container_name: server
    restart: always
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - db
